name: ci-node-workflow
on: [push]
jobs: 
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        js: ['14']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          go-version: ${{ matrix.js }}
      - run: npm ci
      - run: npm run test 
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: r0x00/test-node:latest

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
